# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 682a8d9264855cf3028563621deb13332ee00f3417680e93f11e9ac700f85eea7a5df392eb50a149fb2d36554963cc9eb9efbe19da01afcf10743ad81620eac8

test:
  secret_key_base: 92a9ff15d2849ac1dda4f89b19a32a6c2ce8a039dceb4d2164406e3659904b5ee28b9fa1872346c4555ebeb563e30ce10eb753013ce42ded7eb7c7f811e34a1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
